import type { Chapter } from "../types";

export const marketAwnings: Chapter = {
  slug: "market-awnings",
  order: 1,
  title: "Beneath the Market Awnings",
  subtitle: "Chapter One",
  summary:
    "Before the healer and the captain, there are two brothers above a pottery shop. Drought takes their father's livelihood; the debt outlasts it. A narrative draft of the family's dispossession and the choices that begin to divide them.",
  mood: "gold",
  when: "From Hanno's childhood into the brothers' early working lives",
  status: "draft",
  music: "/audio/ambient-market.wav",
  cover: "/images/chronicle/carthara.webp",
  scenes: [
    { id: "title", kind: "title", heading: "Beneath the Market Awnings", text: ["Chapter One"], mood: "gold" },
    {
      id: "the-fruit-stall",
      heading: "The Fruit Stall",
      pov: "hanno",
      mood: "gold",
      location: "carthara",
      image: "/images/chronicle/carthara.webp",
      text: [
        "The bad fig is underneath. Hanno can feel it before he sees it, a wet patch against his fingers as he lifts the basket onto the stall. He turns the fruit over. Its split has opened all the way to the stalk, and a small black fly walks out between the seeds.",
        "He puts it behind a better one.",
        "His father reaches across the scale and takes it out. Idris does not look at him. He has a customer waiting, a woman carrying a sleeping child against her shoulder, and the right-hand pan has yet to settle.",
        "“These for eating today,” Idris tells her, separating three soft figs. “Those will keep.”",
        "“At your house, perhaps.”",
        "“Then bring them back. My son will eat them.”",
        "The woman looks at Hanno, who cannot tell whether he is meant to smile. She buys the soft ones. Idris wraps them in a broad leaf and takes one small coin less than the balance requires.",
        "When she is gone, Hanno says, “You said not to give credit.”",
        "“That wasn't credit.”",
        "“It was less money.”",
        "His father cuts the spoiled fig in half. “Yes.” He offers Hanno the sound half, then sees the boy's face and puts it down. “Eat it or don't. But don't hide one again.”",
        "“You could have put it underneath.” Hanno points to the leaf his father used for wrapping. “She didn't open the others.”",
        "“She'll open them when she gets home.” Idris wipes his knife. “And come here next time expecting me to cheat her.”",
        "Hanno picks a seed from the wet board. “She might think it spoiled on the way.”",
        "His father looks at him now. Hanno cannot tell which part was wrong: suggesting it, or saying it while customers might hear. “I began with a basket I had to carry home empty,” Idris says. “No stall. No awning. If I had enough for tomorrow's fruit, that was a good day. People learned my name before I could afford this board.” He strikes it with the flat of his hand. Dyia looks up. “I'm not putting it in a parcel with a rotten fig.”",
        "“But you gave her the soft ones.”",
        "“I told her they were soft. She wanted fruit for today.” Idris moves the cut fig to the little dish they keep for themselves. Then he straightens the finest pomegranates along the front, turning their mottled sides inward. Hanno watches him find the best face of each one. When his father asks for the cloth, he passes it without another question.",
        "Beyond their strip of shade, Carthara is opening its shutters. A man on the arcade roof unrolls a red awning with both feet braced against the parapet. The cloth catches the wind, lifts, and falls over the lane. For a moment everyone beneath it is red: the porters with baskets on their backs, the boy washing cups outside the tea shop, Dyia sitting on an empty crate and worrying a loose tooth with his tongue. Higher still, pale terraces climb towards a dome ribbed with green tiles. Hanno has never been inside it. He knows the underside of the market awnings, their patched seams and the pockets where rain collects.",
        "Idris lets him finish setting out the pomegranates. The dates stay in their lidded box until the sun reaches the stall. There is an order to this work that Hanno likes: heavy fruit below, damaged fruit apart, weights returned to their places. From the stool behind the counter he can see a mistake before anyone else can. His father measures the edge of the neighboring booth with his eyes. “Another counter there,” he says. “Figs here, the dates over there. We could take whole loads instead of whatever is left for a man with one stall.” Hanno pictures himself behind the second counter. He likes that his father has said we.",
        "Across the lane, the oil seller taps two fingers on his own empty cash dish. Idris laughs and does the same. Then he turns a folded paper face down beneath the weights.",
        "Hanno has seen that paper before. His father takes it out after supper and runs a fingernail along the columns, sometimes returning to the beginning. Today a red seal shows at the edge.",
        "“Can I have the other half?” Dyia asks.",
        "Hanno pushes the fig towards him. “Cut around the fly part.”",
        "His father begins calling prices. Hanno calls after him, louder, until Idris touches his shoulder and tells him to save his voice for when someone stops.",
      ],
    },
    {
      id: "above-the-pottery-shop",
      heading: "Above the Pottery Shop",
      mood: "dawn",
      text: [
        "Amara has set six jugs on the shelf above their bedding. They have narrow blue lines around their shoulders, broken on one jug where her brush has dragged. Hanno reaches for that one, expecting it to be theirs.",
        "“Not yet,” she says. “They haven't been fired.”",
        "Her wheel stands by the window in the other room. To pass it, everyone must turn sideways, and the wall bears a stripe where wet clay has brushed their clothes. She works with a basin between her knees and her sleeves tied back. Below, the shopkeeper is closing his shutters. They share his kiln when there is room, and when there is no room her pots wait among their clothes and cooking bowls.",
        "Dyia sets a small lump of clay beside her. “A handle.”",
        "“For which pot?”",
        "“Any.”",
        "“Make it fit this one.” She slides a cup towards him. “A finger must go through. More than your finger. Someone might have large hands.”",
        "He studies Idris's hand as their father sits down. Hanno thinks it would be quicker to make the handle himself, but Amara sends him to wash the lentils. As he picks through them, she begins humming. The melody rises where he expects it to fall. He has heard her sing it all his life and cannot sing it back.",
        "“What are the words?” he asks.",
        "She holds her breath to lift a pot from the wheel. “Bring me the board.”",
        "He brings it. When the pot is safe, she draws two steep points in the wet clay beside her basin. “The mountains on Lysandria filled the window where I learned. Two enormous things. I used to judge when to stop for food by the shadow.”",
        "“And if it was cloudy?” Dyia asks.",
        "“The potter beside me would start eating. Then I knew.” Amara smiles at something beyond the room. “She was always borrowing my cutting wire. Once I hid it under my seat and forgot it was there.”",
        "Hanno tries to fit the island she came from around those two marks. In his drawings islands have room for a tree and a boat. He looks at the jugs above their bedding, then at the narrow window. “Was your bench bigger than this?”",
        "“Much bigger. And I still complained about sharing it.” She wipes the little mountains away to make room for Dyia's cup. “Show me that handle.”",
        "After supper, Idris unfolds the paper. Amara dries her hands before taking it, though she has washed them already.",
        "“The carrying charge again?” she asks.",
        "“For the spring stock.”",
        "“We paid for the spring stock.”",
        "“We paid what we could.”",
        "The boys are supposed to be washing bowls. Hanno runs his cloth around the same clean rim while his mother counts with the blunt end of a trimming tool.",
        "“I have the jug order,” she says. “Pay down some of it. Take fewer baskets next time.”",
        "“If the stall looks empty, they go elsewhere.”",
        "“Then let it look empty after midday.”",
        "Idris rubs the bridge of his nose. “The orchard man holds good fruit for me. If I stop buying, he won't. I asked him for the rate he gives the larger traders.”",
        "“And if we keep buying?”",
        "“A larger order earns more.”",
        "Amara turns the paper toward him. “How much of the last one did we sell?” He names the day's takings without needing to look. She nods; she knows he remembers them. “And the day after? Include what you brought upstairs because it wouldn't keep.”",
        "“I know what spoiled.” He pushes her trimming tool away from the column. “You cannot build a business by buying less every time something goes wrong. When I had a basket, they told me a stall would ruin me.”",
        "“This is your stall. I'm asking you to keep it.” Amara waits until he looks at her. “Ask him to reduce the next order. Before he picks it.” Idris says he will speak to him about the charge. Hanno hears the change in the promise. His mother does too, but a drop of water from Dyia's bowl lands on the account, and she lifts it out of reach before she can answer.",
        "Neither of them speaks for a while. Dyia has made a fish with the last of his clay. He presses it against Hanno's wrist, demanding a judgment, and Hanno shakes him off too sharply.",
        "Amara moves the best two jugs to the back of the shelf. “I will keep half the order money for clay and firing. We need something that earns next month.”",
        "Idris folds the paper, carefully matching the corners. “Keep it.” He reaches for Dyia's fish and sets it beside the water bowl, where its head slowly begins to sag.",
      ],
    },
    {
      id: "the-drought",
      heading: "The Drought",
      mood: "storm",
      ambient: "/audio/ambient-wind.wav",
      text: [
        "By the end of summer the fruit arrives in shallow baskets that used to come full. The orchard man breaks open a pomegranate to show Idris the brown membrane inside. They stand over it without speaking, like men who have found damage to something neither of them owns.",
        "The rains have failed inland. Hanno understands this first as a change in the stall: fewer figs, more dried dates, his father standing up whenever a customer slows. Then the water seller raises his price, and Amara begins settling the clay out of her washing basin so she can use the water again. On the arcade roof the awnings gather dust in their empty folds.",
        "Idris tries selling smaller measures. He borrows a handcart and goes through the lanes after the market closes. Hanno walks beside him, calling up to windows where supper lamps are already lit. Sometimes someone lowers a basket on a cord. Mostly they bring the fruit home again, bruised from the wheels.",
        "On the morning Numarius's agents come, Hanno is counting dates into a bowl. His father has promised him the first sale. He has chosen a phrase about sweetness that he thinks will make people stop.",
        "The man with the ledger asks for Idris Averroes. Two others wait behind him with an empty cart. They have not come to buy.",
        "Idris wipes his hands on his apron. “I went to the office.”",
        "“The notice was served.”",
        "“I went twice. They told me to come after the assessment.”",
        "The man opens his ledger on the date box. His sleeve drags across the fruit. He reads out a total that Hanno cannot fit against the money he remembers his father counting.",
        "Idris asks him to read it again. He does. The second time he separates the principal, the charges, the costs of collection. Behind him, one of the men begins undoing the awning rope.",
        "“We haven't finished,” Idris says.",
        "“Move the boy.”",
        "Hanno puts both hands around the bowl. One of the men lifts it away from him and pours the dates into a sack. Dyia appears from the lane with their breakfast wrapped in cloth; he stops so suddenly that the bread slides out onto the stones.",
        "Idris looks at the bread. Then he moves close to the ledger, lowering his voice as if what he offers next is private. “One more season. I will repay all.”",
        "The agent turns a page. Idris keeps talking. He offers the cart, which is borrowed, then the scale, which they have already taken. Hanno waits for the voice he uses with customers, the one that can make a small concession seem like a kindness everyone has chosen. It does not return.",
      ],
    },
    {
      id: "the-fields",
      heading: "Beyond Mercy",
      mood: "void",
      location: "numarius-fields",
      sfx: "/audio/sfx-ember.wav",
      text: [
        "“Your debts are beyond mercy now, fruit-seller.” The agent says it without raising his voice. He taps the place where Idris must put his mark.",
        "Idris reads what is above it. His mouth moves over the words. Hanno can make out Numarius and assignment, and, farther down, fields. When Idris does not take the pen, the agent closes his fingers around it and sets it back in its case.",
        "“You can dispute the balance at the hearing. This is a provisional recovery.”",
        "“When is the hearing?”",
        "“You'll be notified.”",
        "One of the men takes Idris by the elbow. Hanno steps between them, too late to do anything except be moved. His heel catches the empty date box and he falls sitting into it. For a moment his chief feeling is humiliation: Dyia has seen him fall. Then his father is being pulled into the lane.",
        "“Amara,” Idris says. He is trying to turn back. “Tell your mother—”",
        "The man tightens his grip. Idris looks directly at Hanno, who scrambles out of the box. He could run for Amara. He could follow his father. He stays where he is because he cannot decide which one Idris means.",
        "The oil seller stands at the mouth of his shop. Hanno looks at him. The man's fingers have gone pale around the edge of the doorpost. Farther down, another vendor starts calling the price of onions. A woman draws her child against her skirt to clear the lane.",
        "By the time Hanno runs after them, the men have put Idris on a wagon bound for the eastern fields. His father is seated between two strangers. Hanno cannot reach the side through the crowd, and Idris's hand, held out above the wheel, drops before he gets there.",
        "Amara finds the boys at the stripped stall. She asks which office the paper named. Hanno cannot remember. She asks which seal. He begins crying, enraged that she wants answers he did not think to keep.",
        "She kneels and grips his shoulders. “Listen. Did they leave a paper?”",
        "Dyia has it. He has picked it out from beneath the fallen bread and folded the dirty side inward. Amara opens it across her knee. Hanno watches his brother smooth a corner flat for her.",
      ],
    },
    {
      id: "the-apothecary",
      heading: "Master Sinna",
      mood: "forest",
      text: [
        "Amara goes to the office with the paper. She comes back with another. There are days for petitions, days for accounts, days when the man who can answer her is away. She makes pots early and late, fires them when she can, and sells two of her brushes. The boys learn not to ask whether their father is coming home until she has sat down.",
        "When she takes Hanno to Master Sinna, she brings a small lidded jar she has made to his measurements. He turns it in the window light before he looks at the boy.",
        "“You said you needed someone who could count,” she says.",
        "Sinna places two brass weights on the counter. He gives Hanno a dish of seeds and asks for a measure. Hanno has to move one seed back. The master watches his hand until the balance rests.",
        "“Letters?”",
        "“Some,” Hanno says.",
        "Amara says, “He learns quickly.”",
        "“They all do, at first.” Sinna sets the jar aside. “Food here. A place to sleep when the work requires it. A household allowance, after the first month, if he's useful. Materials stay in the shop. So does anything made with them.”",
        "“He comes home one evening in seven,” Amara says.",
        "“If the work—”",
        "“One evening. And you write the allowance down.”",
        "Hanno fears she will lose him the place. Beyond Sinna's shoulder, shelves curve around the room all the way to the ceiling. A narrow stair climbs behind pierced brass screens. There are jars the blue of deep water, paper packets tied with thread, a glass vessel holding a branching white growth that looks almost alive. He wants to know what every one of them does.",
        "Sinna finds a scrap of paper. Amara watches him write. Outside, she gives Hanno a bread bundle and the cup Dyia has made with his too-small handle.",
        "“If he changes the terms, tell me.”",
        "“I can do it,” Hanno says.",
        "She smooths his hair down, then takes her hand away when he ducks. “I know you can work. That is not what I said.”",
        "At first, he washes. He scrubs vessels, sweeps spilled powders into a dish to be inspected, and learns that two things with the same name can come from different harvests and behave differently. Once he reaches towards a pot with a wet spoon. Sinna catches his wrist, explains why it matters, and has him begin again. The master can be patient when there is something exact to explain.",
        "Hanno begins to hear distinctions in the shop's language as he once heard the difference between his father's selling voice and his voice at home. Fresh. Settled. Exhausted. He fills his head with them. At night he falls asleep trying to recall the order of the shelves.",
        "The years of apprenticeship do not pass quickly while he is living them. There are winters of split hands and summers when the upper room is too hot to sleep in. His sleeves are let out and then replaced. He learns to shave the uneven growth along his jaw. Dyia grows taller than their mother and stops asking what Hanno has brought him.",
        "One morning he finds a thin layer floating above a preparation he left to settle. He has been trying to improve it for days. He tilts the jar, hoping the layer will dissolve, but when he sets it down the line appears again.",
        "Sinna comes to inspect the work. Hanno puts the failed jar behind the others, then remembers the fig beneath his father's basket. He moves it back to the front.",
        "“What did you change?” the master asks.",
        "Hanno names the changes. There are three. He expects Sinna to tell him which one is wrong.",
        "Instead the master places an empty jar beside the first. “If it had worked, how would you know which change had helped?”",
        "Hanno looks at the empty jar. He has wanted the work finished. He has thought about a better allowance, about buying a scale like the one the collectors took, about bringing it home without having to explain where the money came from. He has not wanted another morning with the same failure.",
        "He starts again. This time he keeps a jar of the original preparation beside each adjustment and writes down what he has done. Most are no better. One remains clear overnight, and through the next day. He waits until he has made it a second time before carrying both jars to Sinna's desk.",
        "“Better,” Sinna says at last.",
        "The word carries him through a week. Later he fills a whole tray of those jars for delivery beyond the market quarter. The customers pay in the front room. Hanno washes the mixing vessels in the back, planning what he will improve next.",
      ],
    },
    {
      id: "ravash",
      heading: "Ravash",
      mood: "night",
      ambient: "/audio/ambient-night.wav",
      text: [
        "The hearing is always coming. Sometimes there is a notice, then a postponement. Amara keeps them wrapped together beneath a loose tile. After the rains return, Hanno expects the old account to become smaller. When he asks, she puts a finger on a charge for Idris's maintenance in the fields and does not explain it for him.",
        "He is working on something useful at the shop. If he can finish it, if Sinna gives him more responsibility, there might be a larger allowance. He tells her this while she serves supper. She says she hopes so and has him hold the pot because her hand is unsteady.",
        "Later, Dyia meets him on the stairs. His brother smells of dust and the leather straps he has been mending for a carter.",
        "“She was out again last night.”",
        "“Collecting?”",
        "“At that hour?” Dyia keeps his voice low. “She comes back different. Then it's bad again.”",
        "Hanno looks past him to their door. “Have you asked her?”",
        "“She says it's her business.”",
        "“Then let me talk to her.”",
        "“When?”",
        "There is an answer Hanno could give: now. Instead he begins describing a batch that must be watched through the night. Dyia moves aside before he finishes. Hanno goes down two steps, stops, and promises he will come earlier next time.",
        "He hears the name Ravash elsewhere before he lets himself connect it to home. A customer asks for something to settle a shaking hand; Sinna asks a question, then sends Hanno upstairs. In the lane outside, two men argue over a stoppered vial. Hanno starts noticing vials everywhere. Each time his mother is well enough to argue about her firing costs, he is relieved in a way that lets him put off asking.",
        "Dyia begins practising with a sword borrowed from one of the market watchmen. Hanno sees him during a delivery, working through a movement again and again beside a shuttered booth. His brother has grown broad across the shoulders; the weapon no longer looks like something taken from an adult. A captain stops, corrects his stance, and stays to watch him repeat it.",
        "When Dyia tells them he has accepted a place in the guard, Amara puts her cup down. “The guard.”",
        "“Pay every month. Rations. Training.” He directs this list at her, but looks at Hanno. “I can bring food without waiting for someone to sell pots.”",
        "Amara's mouth tightens. He adds, “Without either of you waiting.”",
        "“They took Father,” Hanno says.",
        "“I remember.”",
        "“You'll take someone else's.”",
        "Dyia turns his cup between his hands. “The watchman got the water seller to give the right measure yesterday. He made him do it. I argued with that man all summer and he laughed at me.”",
        "“That isn't the same.”",
        "“No. It worked.” He looks at their mother. “I can learn who handles the petitions. Find someone who will read ours.”",
        "Amara reaches for the pot with both hands. “Bring home your pay first. We will see what else they let you do.”",
        "Hanno leaves before the washing-up. At the bottom of the stairs he can hear Dyia moving the basin. He nearly goes back to help, but he is angry, and the shop is still open.",
      ],
    },
    {
      id: "the-door",
      heading: "The Door",
      pov: "dyia",
      mood: "void",
      sfx: "/audio/sfx-ember.wav",
      text: [
        "Dyia knows where the detail is going before the sergeant turns into the pottery lane. He has read the address on the warrant. He has asked to be posted at the corner and been told to keep walking.",
        "His new collar rubs his neck. Inside his tunic is the name of a clerk given to him by another recruit, a man who might look at the family's account. He has not yet managed to see him.",
        "Amara opens the door with clay on one thumb. She looks first at the sergeant, then at Dyia, as if his presence requires a different explanation. He starts to say that the account is being reviewed.",
        "“It isn't stayed,” the sergeant says. “Stand clear.”",
        "Dyia remains in the doorway. From here he can see the wheel, the bowls drying under cloth, the shelf he repaired when its peg worked loose. Below them, the pottery shopkeeper has come out to watch.",
        "“I can pay something,” Dyia says.",
        "“At the office.”",
        "“Give me until pay day.”",
        "The sergeant steps close enough to speak without Amara hearing. “Your post, or this door. Choose.”",
        "Dyia looks at his mother's hands. He needs the pay. He needs the clerk to answer when he arrives in uniform. If he is dismissed here, he will go to the office in his old clothes, asking the same questions Amara has asked for years. He looks at the warrant again, searching for a mistake he can point to. The sergeant holds out a hand for it.",
        "He steps aside.",
        "Amara walks to the shelf and begins lifting down the finished pots. When the collector reaches for her wheel, she tells him how to remove the basin without breaking it. Her voice is level enough that Dyia wants to take it for forgiveness.",
        "“These aren't hers,” the shopkeeper says from the stairs. He points at a crate of bowls. “They're mine. She was finishing them.”",
        "The collector makes a mark. He leaves two cracked jugs as well, turning them towards the light and then putting them down. Dyia cannot tell whether the shopkeeper is lying about the bowls. He hopes he is.",
        "“There's the back room,” the shopkeeper tells Amara. “Until we arrange something. Mind the damp wall.”",
        "“I can still finish by hand,” she says. “If you leave me space.”",
        "They carry the wheel down in pieces. Dyia moves to take one end of its frame, then stops. Amara has turned to the cupboard where she keeps the boys' cups. She wraps them separately and puts them in her own bag.",
        "Hanno is at the apothecary. Dyia tries to imagine what he will say to him, but every beginning requires him to explain why he is standing beside the sergeant. When the detail leaves, he goes with it.",
      ],
    },
    {
      id: "the-sentencing",
      heading: "The Sentencing",
      pov: "hanno",
      mood: "storm",
      text: [
        "Amara sends word that they are in the pottery shop's back room now. Hanno comes after closing with his allowance and finds the two cracked jugs against a damp wall, stuffed with herbs she is drying. There are bowls on every available ledge. She is shaping small dishes in her lap because her wheel is gone.",
        "He asks why she did not send for him. She says he was working. He presses the coins into her hand, though she has clay on it, and begins promising things he cannot yet afford. She asks him to clear a place to sleep.",
        "She tells him about the hearing instead. This notice has an actual day on it. The magistrate will confirm or discharge the assignment, the paper says. They will bring the receipts. They will ask that the seized property be counted and Idris's work set against the balance.",
        "For once, Sinna lets him leave in daylight. Hanno carries the papers because Amara is afraid she will drop them. At the court there are so many petitioners that they have to stand beneath the outer arcade. The stone is cool against his back. Across the court, a clerk tips a little water onto his inkstone and grinds it while families wait in the sun.",
        "They bring Idris out with a line of other men. Hanno recognizes his walk before his face: the slight forward lean, as if he is easing a cart over uneven stones. His clothes hang loose, and he keeps one hand cupped around the other. Hanno lifts the packet of receipts so his father can see they have come prepared.",
        "Then he sees Dyia beside the magistrate's platform.",
        "His brother's uniform fits better than it did at supper. One hand rests on his belt. Hanno waits for him to look across, to nod, to indicate that he has found the clerk or done whatever it was he promised. Dyia watches the line of prisoners.",
        "The magistrate reads Idris's name and the account. Amara steps forward with Hanno at her shoulder. She asks for the value of the wheel. The clerk tells her that the schedule of recovered goods has been entered.",
        "“At what value?” she asks.",
        "“It is in the schedule.”",
        "She holds out a receipt. “This is what I paid for it.”",
        "The magistrate asks whether she disputes that a debt remains. She begins to explain about the work in the fields. He repeats the question. Hanno can see her trying to find an answer that does not agree to everything she has come to contest.",
        "Idris says, “Let her finish.”",
        "A guard puts a hand against his chest. It is not Dyia. Hanno looks at his brother anyway.",
        "The magistrate confirms the debt and sentences Idris to continued servitude in Numarius's fields. The phrase about discharge upon satisfaction of the account comes at the end, quickly, while the clerk is turning the page. No date is given.",
        "Amara has not put down her receipt. Hanno wants Dyia to take it from her, carry it to the table, make someone look at the sum. There is barely any distance between his brother and the clerk. He says Dyia's name, but it comes out quietly, and a guard has already called the next family.",
        "Dyia looks towards them. His eyes meet Hanno's for a moment and drop. He does not leave his place.",
        "Idris is being led away. Amara goes after him as far as the guards allow. Hanno stays beside the platform, the papers gripped so hard that the folded edges cut into his palm. Around him people are silent. Some stare at the table, some at their own documents. He wants one of them to speak. He wants his brother to move.",
        "At last Amara takes his wrist. He follows her out beneath the arcade. When she asks for the receipts, he has to straighten them before he can let go.",
      ],
    },
  ],
};
