import type { Chapter } from "../types";

export const bitterApprenticeship: Chapter = {
  slug: "bitter-apprenticeship",
  order: 2,
  title: "The Bitter Apprenticeship",
  subtitle: "Chapter Two",
  summary:
    "Hanno learns what careful work can mend and what his master can charge for it. At home, a broken bowl brings the brothers' different accounts of sacrifice into the same room.",
  mood: "forest",
  when: "The years after the sentencing",
  status: "draft",
  music: "/audio/ambient-night.wav",
  cover: "/images/chronicle/apothecary.webp",
  scenes: [
    { id: "title", kind: "title", heading: "The Bitter Apprenticeship", text: ["Chapter Two"], mood: "void" },
    {
      id: "a-world-unto-itself",
      heading: "A World Unto Itself",
      pov: "Hanno",
      mood: "void",
      text: [
        "The stain will not leave the basin. Hanno has worked at it since the lamps in the arcade went out, using first a cloth and then a folded scrap of rough linen. Brown water runs over his wrists. Above him the apothecary's glass catches the first light: blue flasks, narrow green bottles, a clear vessel holding something pale and branched that turns slowly when a cart passes outside. He once thought the shelves contained every possible answer. This morning they contain several hundred things he must dust.",
        "Sinna sets his cup beside the basin. ‘You have polished the surface around it.’ He puts a finger into the stain and smells it. ‘What was prepared here yesterday?’ Hanno names the remedy. ‘And what does its residue become when you add hot water?’ He knows the answer as soon as the question is complete. He has made his task harder by trying to finish it quickly.",
        "The master does not strike him. That would be easier to resent. He makes Hanno explain the mistake, sets aside the spoiled cleaning water, and waits while he starts again. Through the open shopfront comes the clatter of a porter unloading jars. The porter's left hand is wrapped in a cloth stiff with yesterday's blood. He asks whether Master Sinna will look at it before the next delivery. Sinna tells him to sit.",
        "Hanno holds the lamp while the wrapping comes away. The porter apologizes for the smell, then for the blood on the stool, then asks the price. ‘Keep still before you bargain,’ Sinna says. His voice has changed. He asks when the hand was injured and what work the man has continued doing. He listens to the answers. When the porter flinches, he stops rather than telling him to endure it.",
        "While the man rests, Sinna gives Hanno a sheet for the case record. Hanno writes that a defective handle caused the injury. The master points to the sentence. ‘Have you seen the handle?’ ‘He told us it slipped.’ ‘Then record what he told us.’ Beneath that, Hanno describes what they can see. He begins a third line with an explanation, and Sinna has him mark it as a possibility. The three accounts occupy different places on the page. None is to disappear merely because the others seem more convincing.",
        "Hanno fetches clean cloth, then the wrong jar. Sinna catches his wrist before he can open it. ‘Read.’ Hanno reads. ‘Again, without deciding what it ought to say.’ The correct jar stands one shelf lower. Later, when the hand is dressed, the porter turns it in the light with an expression Hanno remembers from his father finding good fruit beneath a damaged top layer. Something expected to be lost has become usable again.",
        "The man leaves two small coins and promises the rest after his deliveries. Sinna enters the debt in a narrow book. Beside it lies a larger book with brass corners, the one he closes whenever Hanno comes near. ‘You see?’ the master says. ‘Precision first. Gratitude follows.’ Hanno watches the porter's shoulders ease as he walks away. He thinks the two belong together. He carries that thought back to the basin and works until the stain lifts.",
      ],
    },
    {
      id: "respect-every-ingredient",
      heading: "Respect Every Ingredient",
      pov: "Hanno",
      mood: "forest",
      text: [
        "Winter rain finds a crack above the rear shelves. By the following summer Hanno can identify the damp jars before he touches them. He learns to keep records of work that fails, although failure is the part he most wants to omit. He learns that two plants with the same common name can behave differently, that a patient may describe pain badly without lying, and that a clean instrument is useful even when nobody has praised the person who cleaned it.",
        "In a cupboard above the case records, Sinna keeps the unfinished gatherings of his medical compendium. One concerns the body's ordinary functions, another the materials used in treatment, another the ways a familiar illness can be mistaken for something else. Hanno is allowed to consult them. He often finds the master working there after closing, a book of logic open beside a dispute about how a mineral changes under heat. Asked which passage should go into the compendium, Sinna makes him explain what a reader would need to know first. Hanno rearranges three pages. For the first time, he understands why the master spends so long on the order of things he already knows.",
        "He keeps returning to the preparation he first improved, the one that used to separate in its bottle. The ingredients are Sinna's; the problem occupied apprentices before him. Hanno's first success has not made every batch reliable. When he thinks he has finally corrected it, Sinna holds a bottle against the window, shakes it once, and waits. Hanno waits with him, scarcely breathing. ‘Do it again,’ the master says.",
        "He repeats the work until the result no longer depends on a lucky afternoon. A patient who has struggled to take the old remedy accepts the new one without gagging. ‘It works,’ Hanno says. Sinna asks what works. ‘He can take it.’ ‘Then put that down. We have not yet seen what it does for his illness.’ Hanno adds another line to the record, leaving space for the patient's return. That small success keeps him at the bench past closing. Soon there are other improvements, most discarded, two retained. The larger discoveries he imagines remain beyond him. The little ones are real enough to make leaving the workshop feel like abandoning a conversation just as it becomes interesting.",
        "One evening a servant comes through the side door for six bottles tied with gold cord. Hanno recognizes the cloudy green remedy inside them. The servant pays with a weight of silver greater than Hanno's allowance for several months. Sinna slips the money beneath the brass-cornered book. ‘An old account,’ he says before Hanno has asked. ‘Their household is often late.’ The labels bear the master's seal. Of course they do. This is the master's shop.",
        "Hanno asks whether there might be more money for Amara that week. Sinna looks up from the labels. ‘And who paid for the jars you cracked learning that preparation? Who paid for the ingredients that went into the gutter?’ He asks without raising his voice. Hanno can remember each failure. He cannot see the receipts for the successful batches. The arithmetic belongs to the person with the book.",
        "Sinna gives him a little extra and calls it an advance. Hanno thanks him. On the way home he buys oil and a packet of dried fruit, then waits while a bread seller cuts the cheaper loaf. He misses the first part of the evening meal. He has missed it often enough that Amara no longer keeps his portion warm. The borrowed back room is smaller than the rooms they lost, and he sees his absence as one less person taking up its air.",
        "At the bench next morning he copies his observations into a notebook made from discarded sheets. He does not write that he invented anything. Sinna has taught him how many hands stand behind a useful remedy, and Hanno believes him. What troubles him is that only one name appears on the bottles. He turns the page before the trouble can become a question he would have to ask aloud.",
      ],
    },
    {
      id: "the-alleys",
      heading: "Into the Alleys",
      pov: "Dyia",
      mood: "night",
      text: [
        "Dyia sees his mother beneath the awning of a closed basket shop. At first he thinks she is waiting for someone to carry an order home. She has begun making small pieces by hand where she can borrow a patch of table: shallow dishes, little cups, work that does not require the wheel. There is usually a bundle beneath her arm. Tonight there is none.",
        "He has come off a long patrol. His belt has rubbed a sore place above his hip, and he wants the barracks water and the simple relief of taking his boots off. Then Amara looks behind her. He moves into the shadow of a pillar before he has decided to follow. He tells himself she may need help. When she enters a narrow passage beside the basket shop, he goes after her without calling her name.",
        "The man at the far end wears an ordinary brown coat. That surprises Dyia. He has imagined the people who sell Ravash as recognizably separate from the people who sell lamp oil or mend shoes. This man has a split thumbnail and a parcel tucked beneath his arm. Amara opens her hand. He counts her coins with his thumb and says she is short.",
        "‘It was enough last time.’ Her voice carries clearly between the walls. ‘Last time you bought less.’ ‘Then less.’ The man glances toward the street. ‘That is less.’ Dyia's hand closes around the end of his belt. He could step out now. He could make the man open his parcel. He imagines Amara seeing the uniform before she sees her son, and for a moment he cannot move.",
        "She takes a thin copper ring off her finger. Dyia recognizes it as something she wears to hold a loose thread when she works. The man examines it, shrugs, and puts a small vial into her palm. He does not threaten her or laugh. He merely completes the exchange. Dyia has no idea where his superiors would enter a transaction that leaves nothing to seize but the little she was willing to surrender.",
        "He follows her back by a different street. At the fountain she stops to drink and has difficulty holding the cup. A woman beside her steadies it without asking why. Dyia wants to thank the woman and also wants her gone. He dislikes how much of his mother's life takes place among strangers who know things he has not been told. He thinks of Hanno surrounded by clean glass, congratulating himself on the money he brings home.",
        "At the borrowed room he reaches the door before Amara can close it. ‘Who was he?’ he asks. She does not pretend to misunderstand. She looks first at his hand on the door, then at his face. ‘Move your arm.’ ‘Tell me his name.’ ‘You can speak to me inside, or you can question me in the street in front of the neighbors. But you will let me enter my own room.’ He moves. The permission feels like a defeat, and he is ashamed of that before he follows her in.",
      ],
    },
    {
      id: "something-breaking",
      heading: "Something Breaking",
      pov: "Hanno",
      mood: "ember",
      ambient: "/audio/ambient-ember.wav",
      sfx: "/audio/sfx-ember.wav",
      text: [
        "Something breaks before Hanno reaches the room. He hurries along the passage, his packet of herbs knocking against his knee. Dyia stands beside the table. Amara is seated with one hand closed in her lap. A newly fired bowl lies in three pieces on the floor. There are unglazed cups on a board by the damp wall, the small work she has managed since they lost the wheel.",
        "‘What happened?’ Hanno asks. ‘Ask her.’ Dyia points at Amara's hand. ‘Or perhaps you have somewhere else to be.’ Hanno puts the herbs down. ‘Don't speak to her like that.’ ‘Then speak to her yourself. When did you last do that without counting what you brought home?’ Amara says Dyia's name. He goes on as if she has said nothing.",
        "‘I see her at night. I see what this costs. You arrive with your little packages and then disappear. You abandoned us.’ Hanno feels the heat rise into his face. His fingers smell of the remedy he has spent fourteen hours making. He had thought of the packet of herbs as a useful gift. Now he cannot bear to look at it. ‘I was working to feed you.’ ‘I had work today too.’ ‘In their colors. You stood in their colors while they took him.’",
        "For a moment the room becomes very still. Dyia looks toward their mother. Hanno sees the glance and mistakes it for a plea that she defend him. ‘Tell me what staying was worth,’ Hanno says. Amara places the vial on the table. ‘He was at the door.’ She says it quietly, with no force left over for making sure either son understands.",
        "Hanno knows which door. He helped carry the bedding when they moved. Amara had told him only that the men came while he was at the workshop. Dyia had brought bread afterward. He remembers accepting it. ‘You let them take her things?’ Dyia's mouth opens. Hanno steps toward him. ‘You brought us bread here and let me thank you?’",
        "The blow catches him beside the mouth. He strikes the wall shoulder first, bringing down the board that holds Amara's cups. Dyia is on him before he can get his breath. There is no skill in the fight. They seize cloth, slip in the broken pottery, collide with the table. Hanno gets an arm across Dyia's chest and drives him back against the wall. Dyia hits his ribs with the heel of his hand. Somewhere close by, Amara is telling them to stop.",
        "Hanno hears her properly when she says, ‘Those were ordered.’ The cups. He is standing on one of them. He loosens his grip and Dyia shoves him away. Blood from Hanno's lip drops onto the glaze of the first broken bowl. Amara does not look at either of them. She reaches for the broom. Hanno catches it before she can stand. ‘I will do it.’ ‘You will pay for them,’ she says. ‘Both of you. And you will stop deciding that whichever of you speaks loudest has cared for me best.’",
      ],
    },
    {
      id: "go-then",
      heading: "Go, Then",
      pov: "Dyia",
      mood: "ember",
      text: [
        "Dyia cannot make his right hand uncurl. He holds it behind his leg while Hanno sweeps. A broken cup turns in the dust, showing the little mark Amara presses into the foot of every piece. He remembers carrying her old wheel down the stairs with the others watching. No: he did not carry it. He stood aside while they carried it. He has returned to that distinction often enough to know how useless it is.",
        "‘There would have been another guard,’ he says. Hanno stops sweeping. ‘What?’ ‘If I refused. There would have been someone else at the door, and I would have lost the post.’ He hears the words as his sergeant said them. Hanno looks at him for so long that Dyia wishes his brother would hit him again. ‘Did the post bring the wheel back?’ Hanno asks.",
        "Amara takes the dustpan from the wall. ‘I need the room quiet.’ ‘Mother—’ ‘Quiet, Dyia. You have asked me nothing tonight that you were willing to hear the answer to.’ He wants to tell her he saw the man, that he can find him again, that there is something he can still do. He also wants her to tell Hanno about the meals he carried, the mornings he waited with her, the times there was nobody else. He hates himself a little for wanting a witness so badly.",
        "Hanno says he may be sent away to buy materials. It is not quite an announcement. Dyia understands that his brother has been saving it for some calmer evening that never comes. ‘For Sinna?’ ‘At first.’ ‘And then?’ Hanno does not answer. In that silence Dyia hears a future being kept available for one of them. ‘Go, then. Chase your dreams of glory and wealth. I'll clean up the mess you left behind.’",
        "Hanno sets down the broom. For an instant Dyia thinks they will begin again. Instead his brother kneels to pick up a piece too large for the pan. The refusal leaves Dyia with nowhere to put his anger. He lays money on the table, more than his share of the broken work, because he cannot calculate it now. Amara does not thank him. He had no right to expect thanks, but he notices its absence all the same.",
        "Outside, the fountain has been shut for the night. Water runs in a thin line along the drain toward the lower streets. He follows it until the barracks lamps appear. A sentry asks about the cut over his knuckle, and Dyia says he caught it on a door. The lie comes easily. He can feel the shape of the guard's ordinary account waiting to receive him: a patrol completed, a hand injured, a man fit for duty.",
        "In his bunk he studies the brown-coated seller's face until he is certain he will remember it. Split thumbnail. Left cheek rough where the razor missed. He tells himself this is useful knowledge. Tomorrow he will find the man who took Amara's ring. He does not let himself consider why it is easier to pursue that stranger than return to the room and ask his mother what she needs.",
      ],
    },
  ],
};
