import type { Chapter } from "../types";

export const giftOfLysandria: Chapter = {
  slug: "gift-of-lysandria",
  order: 4,
  title: "The Gift of Lysandria",
  subtitle: "Chapter Four",
  summary:
    "Five years of alchemical work on the island of Lysandria lead Hanno to a child's bedside, a public honor, and a healer whose obligations are not his to decide. On the nearby Moonlit Isle, they choose a life together.",
  mood: "storm",
  when: "Five years on Lysandria",
  status: "draft",
  music: "/audio/ambient-wind.wav",
  cover: "/images/chronicle/lysandria.webp",
  scenes: [
    { id: "title", kind: "title", heading: "The Gift of Lysandria", text: ["Chapter Four"], mood: "storm" },
    {
      id: "ancient-guardians",
      heading: "Ancient Guardians",
      pov: "Hanno",
      mood: "storm",
      location: "lysandria",
      image: "/images/chronicle/lysandria.webp",
      text: [
        "General Phylios has a broken pruning knife on his table. Hanno notices it before the military maps, because the handle has been repaired with a strip of wire and the general could plainly afford another. Phylios catches him looking. ‘The gardener wants the same weight when it is mended. The smith keeps offering her a better one.’ He moves it aside to make room for Hanno's samples.",
        "Through the open shutters Hanno can see the island's two enormous mountains. One rises beyond the roofs; the other seems to stand farther out in the light, although both belong to the same land. His mother described a pottery bench with both in view. He has been looking for that arrangement of peaks since the boat brought him to Lysandria, discovering how much of her description he failed to remember. He means to write about them before he fills another letter with purchases.",
        "Hanno explains what Sinna requires. Phylios asks what Hanno knows about the people who extract it. He describes the work he has seen and the symptoms the foundry's healers are recording. When he reaches the edge of his knowledge, he says so. The general listens with the attentive stillness Hanno has encountered in good practitioners, then asks what Hanno would need in order to learn more.",
        "The arrangement is modest. He can remain at the foundry, receive lodging and payment for specified work, and buy a limited allotment through the ordinary accounts. He will not have unrestricted access because he has pleased the ruler. Hanno almost laughs with relief. The terms are less generous than the opportunities he has imagined and much clearer. He asks for them in writing. Phylios rings for a clerk.",
        "The foundry yard shares a wall with a practice court. Occasionally Hanno joins a lesson before work, using a wooden staff like the one he carries on rough roads. He learns to keep his footing, turn aside a blow, and leave himself room to retreat. When an exercise becomes a contest, he wants to win it and sometimes forgets its purpose. An instructor has to remind him that arriving home uninjured will serve him better than finishing an argument with a stranger.",
        "He stays five years. Most of them belong to alchemy: unfamiliar materials, case papers, observations copied and tested, mistakes he no longer has ignorance to excuse. Shipments go back to Carthara with accounts and money for home. Sinna sends shorter letters when the quantities fall below his hopes. Hanno's local earnings let him buy books and materials without asking the workshop, although his old commission still occupies a corner of every decision. He takes occasional lessons in self-defense and becomes competent enough to protect himself. It remains a practical skill, not the work by which he measures his life.",
        "In the fifth year he is paid to assess a consignment whose quality the seller has exaggerated. He wants the fee, and would like the seller to continue bringing him business. He also wants the assessment to be right. He makes two columns in his notebook and works until the result will not flatter the man who supplied it. When Phylios's messenger comes for him that evening, he assumes the disputed consignment has reached the general. Then he sees the messenger's face and closes the book.",
      ],
    },
    {
      id: "the-spear",
      heading: "Zaharaz",
      pov: "Hanno",
      mood: "gold",
      location: "lysandria",
      image: "/images/chronicle/lysandria.webp",
      ambient: "/audio/ambient-ember.wav",
      sfx: "/audio/sfx-ember.wav",
      text: [
        "The general's son lies beneath a sheet printed with little boats. One foot has escaped it. Hanno notices the dirty heel, the ordinariness of a child who had been running somewhere before this room became the whole world. Two household healers stand beside the bed. Neither looks relieved to see another person summoned. One asks what he has brought; the other puts the record of the boy's illness into his hands.",
        "He reads before speaking. They have kept the fever from climbing unchecked, managed the hours in which the child could not drink, and stopped a treatment that made him worse. They have not found what will turn the illness. Hanno recognizes a pattern he studied in the foundry's old case papers, though the boy has none of the workers' history. He asks another question, then another. The older healer answers the third by showing him a page he has skipped.",
        "Phylios waits at the doorway. ‘Can you help?’ Hanno can think of an approach they have not tried. That is not the same as knowing it will succeed. He says both things. The general looks at the household healer, who asks Hanno to explain the reasoning. For several minutes the three practitioners argue without making the father understand more than the fact that they disagree. Then the older healer draws a line beneath the last entry and gives Hanno space at the preparation table.",
        "The work consumes the night. Hanno does not perform it alone. Someone checks each label, someone keeps the boy comfortable, someone catches the mistake he makes when exhaustion causes him to repeat a measurement in his notes. He prepares the unfamiliar remedy from the materials available in the household stores, adjusts it in response to the observations they share, and waits through an hour in which nothing seems to change.",
        "Near dawn the child asks for water in an ordinary, irritated voice. Hanno is so afraid of mistaking the improvement that he does not move. The younger healer brings the cup. Later the boy complains about the sheet. Later still he sleeps without the terrible effort that has filled the room. Hanno goes into the passage and discovers he is crying. He presses the heels of his hands against his eyes until somebody passing quietly gives him a cloth.",
        "The public thanks comes after the boy's strength begins to return. In the open court Phylios gives Hanno a traveler's staff: sound wood, a comfortable grip, a simple ferrule to protect the end on stone. The name Zaharaz is cut near the grip. ‘For your next road,’ he says. ‘And for what you restored to this house.’ Hanno had expected something he would have to keep safe from ordinary use. He closes his hand around the staff and imagines it taking some of his weight on the descent to the harbor.",
        "There is no marvel hidden in the wood. What changes the afternoon is the general saying his name before the gathered people. Hanno names the two healers in return. The crowd applauds that too, but it is his name they call across the court. He rests the staff against his shoulder and raises his free hand. The applause rises. He had not known that relief could be followed so quickly by this other appetite.",
      ],
    },
    {
      id: "alethea",
      heading: "Alethea",
      pov: "Alethea",
      mood: "dawn",
      text: [
        "Alethea recognizes the man who wept in the passage. In the court he has straightened his shoulders as though he is trying to occupy the space the applause has made for him. People keep bringing him cups he forgets to drink. She has come to the celebration after a morning seeing patients below the foundry and still has a spot of salve on her sleeve. A woman beside her says the foreigner performed a miracle. Alethea says the household healers did very good work keeping the child alive long enough for him to attempt anything.",
        "He hears her as the crowd parts. For an instant she expects offense; she has given it before without intending to. Instead he asks whether she knows them. She does. He wants to know if the older healer has slept. That is the first thing she likes about him in daylight.",
        "‘You have had half the city tell you what a gift you possess,’ she says. ‘Has anyone asked whether you have eaten?’ He looks at the untouched cup and admits that they have, several times. She leads him to a table where the food is being cleared. There are olives, bread, and the broken end of something sweet. He eats without pretending he has been too elevated by the occasion to be hungry.",
        "She asks about the illness. He begins with the preparation, stops himself, and begins again with what the other healers had already established. She likes that too. When he asks about her work, she tells him about the foundry families, the old patients who cannot manage the upper stairs, and a room she has been trying to secure closer to them. The owner wants more rent than her practice can cover. Hanno offers to speak to Phylios. ‘I have asked about rent,’ she says. ‘You have offered me a patron.’",
        "He considers the difference. She can see him doing it. Most people merely assure her their patron would be unusually generous. A few days later he comes to the lower practice with a repaired carrying case for her glass and an offer to do paid preparation work at an ordinary rate. He says she can refuse. She inspects the case, finds the hinge sound, and accepts the work.",
        "Over the following months they become acquainted in inconvenient hours. She learns that he forgets to eat when a problem absorbs him and can remember an exact price from three years ago. He learns which of her silences means concentration and which means that she has already told him something he has chosen not to hear. They disagree about whether a patient who misses a visit has broken a promise. She makes him walk the steep route from that patient's house before they finish the argument.",
        "One evening he tells her about his father, the stall, the brother in uniform. She does not say the suffering has made him better. She asks what has happened to his mother. He takes a letter from his coat, and his uncertainty becomes something they can actually discuss. Alethea loves him before she is certain it is wise. She does not confuse the two. When he asks to see her on a day neither of them is working, she makes him choose a time and promise to arrive without his account book.",
      ],
    },
    {
      id: "the-elysian-flower",
      heading: "The Elysian Flower",
      pov: "Hanno",
      mood: "night",
      location: "moonlit-isle",
      ambient: "/audio/ambient-night.wav",
      text: [
        "The boatman says the sea will be quieter after moonrise, and for once Hanno does not try to improve somebody else's schedule. He and Alethea leave Lysandria's shore with two friends from her practice and a basket of food. The two great mountains remain behind them as the smaller Moonlit Isle emerges ahead. Its terraces are white in the moonlight. Low plants spill over their walls, and below them the water carries such a clear reflection of the sky that Hanno has to look twice to find the horizon.",
        "They have chosen a small ceremony. Hanno had offered a larger one after Phylios's gift made invitations seem easy. Alethea asked whom he wanted there, and he discovered he was naming people he wanted to witness his good fortune rather than people with whom he wanted to share it. He writes to Amara before they leave for the island. Her reply will not arrive in time. He keeps the letter he wishes he could receive folded in his imagination beside the one he has actually sent.",
        "They speak their promises beneath a stone arch warmed by the day. The island woman who keeps the terrace asks each of them to say what work they mean to undertake together. Alethea says care, then adds that she intends to remain a person who can disagree with her husband. Their friends laugh; Hanno does too. He promises to hear her. It seems a simple promise in this place.",
        "Afterward, while the others unpack the food, he sees the flower beside the wall. Red petals turn to yellow near their base. He knows it from a carefully preserved drawing: the Elysian flower, rare enough that two of the books he owns disagree about its properties. He crouches without touching it. Alethea kneels beside him. ‘Is it what you think?’ she asks. ‘I think so.’ ‘Then let us leave some room for being wrong.’",
        "The terrace keeper knows which patch can spare a bloom. With her permission Hanno takes one and sets it behind Alethea's ear. Moonlight catches the yellow where the petals rest against her hair. For a time he forgets the books, the properties, and every use a flower might have beyond being beautiful to someone he loves.",
        "In the morning he asks about taking a small rooted cutting. The keeper names a price for the plant and instructions for its care, then refuses when he points toward the fuller wild patch. They buy the cutting from her tended bed. It will travel in a little clay pot, and it may not survive Carthara. Alethea carries it back to the boat while Hanno takes the basket and uses Zaharaz to steady himself on the damp steps. Their small purchases require more attention than either had anticipated. He is happy to give it.",
      ],
    },
    {
      id: "hand-in-hand",
      heading: "Hand in Hand",
      pov: "Alethea",
      mood: "dawn",
      text: [
        "Leaving takes longer than marrying. Alethea has patients who will need someone next week, a room paid for through the season, and unfinished arrangements that cannot be folded into Hanno's luggage. He says they can delay. She tells him that delay is not the same thing as making provision. Together they sit at her worktable and list what must happen before she can go.",
        "One colleague will take the morning visits if another can cover the lower streets. A patient refuses the first person Alethea suggests because of a quarrel that has nothing to do with medicine. She finds someone else. The carrying case Hanno repaired stays with the practice. When he looks surprised, she reminds him that the case was useful before either of them imagined their departure.",
        "She intends to work in Carthara. She has said this plainly enough that Hanno repeats it to his acquaintances, but she suspects he imagines her work arranged around his. One evening she lays that concern between them. ‘Your mother is one person I hope to help. She cannot be my entire reason for being there.’ He looks hurt before he looks thoughtful. She waits through both expressions.",
        "‘And if you hate it?’ he asks. ‘Then I will tell you.’ ‘I cannot promise the city will be fair.’ ‘I have not asked for that promise.’ What she asks is that money for their work be discussed, that disagreement not be treated as disloyalty, and that his need to return not become her duty to stay regardless of what she finds. He agrees. She loves him more for agreeing without making a speech, and knows agreement will still have to become conduct.",
        "On the last morning the general's son comes to say goodbye. He is healthy enough to be irritated at having been made to dress properly. He wants to carry Hanno's staff and discovers that it is inconveniently tall for him. Hanno walks beside him until they reach the end of the terrace, then takes it back when the boy decides he would rather run. Alethea watches the patient insist on being a child again, which strikes her as a better sign than any public blessing.",
        "The descent to the coast takes them past her old practice. Somebody has already opened the shutters. The sight hurts and reassures her in equal measure. At the quay she checks the flower's soil while Hanno checks the baggage tally. When he offers his hand, she takes it. She is going with a man she has chosen toward work she has also chosen. Behind her the shutters remain open after the road turns and she can no longer see them.",
      ],
    },
  ],
};
