import type { Chapter } from "../types";

export const theCure: Chapter = {
  slug: "the-cure",
  order: 5,
  title: "A Cure and Its Consequences",
  subtitle: "Chapter Five",
  summary:
    "Back in Carthara, Hanno and Alethea struggle to turn a promising treatment into lasting care. Amara begins to recover, the city learns his name, and powerful people begin counting what his success costs them.",
  mood: "forest",
  when: "The return",
  status: "draft",
  music: "/audio/ambient-market.wav",
  cover: "/images/chronicle/apothecary.webp",
  scenes: [
    { id: "title", kind: "title", heading: "A Cure and Its Consequences", text: ["Chapter Five"], mood: "forest" },
    {
      id: "return",
      heading: "The Return",
      pov: "Hanno",
      mood: "gold",
      location: "carthara",
      image: "/images/chronicle/carthara.webp",
      text: [
        "The harbor charges him for the flower. Hanno explains that it is one small plant in a pot, worth less than several things the clerk has already waved through. The clerk explains that those things occupy different lines of his schedule. Behind Hanno, Alethea puts down her bag. He can hear her trying not to laugh. ‘Welcome home,’ she says after he pays.",
        "Carthara rises above the quay in layers of white stone, colored awnings, and gardens Hanno remembers as bare rooftops. A new arcade carries water through narrow brass mouths into a shaded basin. Boys are rinsing delivery cups at its edge. Beyond it, in the older streets, the paving still holds the hollow worn by his father's stall. He looks for it without meaning to and then wishes he had been watching Alethea's first impression of the city instead.",
        "Sinna counts the cases before offering them seats. He asks after the metals, the preserved plants, the losses on the route. Hanno lays out the copies of his accounts. The master dislikes the copies. ‘You have grown particular.’ ‘There was money to account for.’ ‘My money.’ Hanno puts the final statement beside the first commission. There is enough from his independent Lysandrian work to settle the disputed balance if he accepts the master's calculation. He knows that calculation favors the workshop. He also knows how long an argument could keep him attached to it.",
        "Through the new doorway he can see crates bearing the nursery's mark stacked above the cool floor. A clerk is entering orders at the second bench. Sinna now owns the upper rooms as well; the old landlord's plate has been removed from the stair. Hanno recognizes the remedies on the counter by their color and by the little sediment he never quite eliminated. His improvements have paid for rooms he has not entered. The supply arrangements he spent months negotiating have kept them stocked.",
        "Sinna lays a letter from the nursery beside the account. It is addressed to Hanno and has been opened. A damaged consignment needs a decision about the carrier's payment. ‘Tell them to write to the shop in future.’ ‘They did write to the shop.’ Sinna taps the name. Hanno reads the keeper's description of the damage before answering. ‘I'll give you the terms we agreed. She will want whoever answers to have read them.’ He makes a copy of the letter. He has no order of his own to send her, and no reason to believe she would give him better terms. But she knows whose reply she is waiting for.",
        "He pays, asks for a receipt that closes the commission, and waits until Sinna signs. The silence while the ink dries is longer than their greeting. When Hanno introduces Alethea as a healer, Sinna asks whether she will assist in the shop. ‘We are finding rooms for our own work,’ she says. Hanno is grateful she says it before he can make independence sound like an apology.",
        "Amara is still in the borrowed back room. She looks smaller seated beside the damp wall, with a shawl he does not recognize across her knees. He kneels to embrace her and feels the bones of her shoulder through the cloth. She holds him for a long time. Then she asks why he has brought a staff into a room already too small for three chairs. He laughs too quickly and has to begin the embrace again.",
        "Later she shows him a notice delivered while he was in Lysandria. She had sent word with a merchant before she knew Hanno had left; the news and the travelers have passed without meeting. Idris's labor account has been closed by death. There is no account of an illness, no place of burial, no final word. Dyia asked for more and was told there was nothing further to give. Hanno reads the notice standing up, then sits because his legs have become unreliable. He had prepared for this knowledge on the journey. The paper makes all that preparation useless. He asks to keep it; Amara says he may make a copy.",
        "She studies Alethea without pretending not to. ‘He wrote that you were sensible.’ ‘I wrote that she was wise,’ Hanno says. Amara dismisses the distinction with a finger. ‘We shall see.’ On the table stands a half-finished cup whose edge has collapsed where her hand shook. Hanno wants to hide it from their visitor. Alethea asks whether she may move it to make space, and waits for Amara to answer.",
        "They rent a small ground-floor workshop with living space behind it. Hanno chooses it for the light. Alethea checks the door's width, the water, and whether a person unable to climb stairs can reach them. Together these seem sensible requirements. He does not yet understand how often they will disagree about which one matters most.",
      ],
    },
    {
      id: "a-city-in-despair",
      heading: "The Cost of Relief",
      pov: "Alethea",
      mood: "void",
      ambient: "/audio/ambient-night.wav",
      text: [
        "Alethea's first Cartharan patient arrives to ask whether Hanno is there. He is out buying shelving. The man begins to leave, then sees the clean seat and changes his mind. He works carrying water to houses that do not receive the new arcade's supply. Lately his hands shake so badly he has broken two customers' jugs. He wants something that will let him finish his route.",
        "She asks what he has already taken. He looks at the door. She closes it enough to give him privacy and asks again. Ravash enters the conversation reluctantly, as though naming it might bring another creditor into the room. He describes hours of relief and the need that follows them. She has seen forms of dependence before; she does not assume that makes this substance familiar. She records what he tells her and what she can actually observe.",
        "Over the next weeks the same request arrives in different clothing. Let me work today. Let me sleep tonight. Let me appear at my sister's wedding without anyone noticing. Some people have been using Ravash for years; others began recently. Several return after missing a visit and expect to be scolded. Alethea asks what made returning difficult. The answers include money, shame, a child needing care, and one employer who will not permit time away.",
        "Hanno wants to understand what Ravash does. She wants that too, but also needs somewhere to put the people waiting while he studies it. They turn the storage alcove into another place to sit. A woman from the neighborhood agrees to keep appointments and receipts for wages they can barely afford. Alethea starts a daily book for treatments dispensed and a separate record for follow-up observations. Hanno asks whether one book would do. ‘Not if the account of what they owe crowds out the account of how they are.’",
        "Amara comes only after Alethea visits her. She does not want to be displayed as the first reason her son returned. ‘He thinks if he brings enough home, what happened will unhappen,’ she says. Alethea asks what she wants. Amara looks toward the covered clay. ‘A whole morning's work. Then to decide what to do in the afternoon without bargaining with that little bottle.’",
        "Hanno lays his early notes before them that evening. He has an approach to a treatment, derived from the alchemy he has spent years studying, and no proof yet that it will help. Amara listens while he describes his hopes. Alethea asks him to describe the uncertainties as carefully. He stiffens, then does it. Nothing will be given without Amara agreeing; every attempt will be recorded; an adverse response will stop the work until they understand more.",
        "‘And if I say I have had enough?’ Amara asks. Hanno looks at her, appalled that he might be mistaken for someone who would refuse. Alethea waits. ‘Then we stop,’ he says at last. Amara nods. ‘Say that again when you are disappointed.’",
      ],
    },
    {
      id: "trials",
      heading: "Trials",
      pov: "Amara",
      mood: "forest",
      text: [
        "The first preparation gives Amara three quiet hours. She remembers them with an intensity that makes the following night feel like theft. Hanno asks when the discomfort returns, how it changes, what she can bear to eat. She answers until the questions begin to sound like a demand that she give the experiment something useful. Then she tells him she wants to lie down.",
        "Other attempts bring less relief. One leaves her so weak that she cannot sit upright. Hanno reaches for his notes, then for another jar. Alethea puts a hand on the worktable between him and it. ‘We stop here.’ He says the response tells him what needs to change. ‘It tells us your mother needs care.’ For a moment Amara can see the boy who used to insist a cracked cup could still be mended while water ran through it.",
        "She does not take another preparation that day, or the next. Alethea attends to her and asks Hanno to leave the room long enough for Amara to speak without managing his face. Amara says she is frightened of disappointing him. Saying it makes her angry. She has lost enough without adding responsibility for the hope he has placed in her body.",
        "When they speak again, Hanno apologizes without using the word but. He explains what he believes happened and what he still cannot account for. He has discarded the preparation that harmed her. She asks whether he would have stopped so quickly if a stranger had been in her chair. He looks down. It is not the answer she wants, but she prefers it to a handsome lie.",
        "Weeks of slower work follow. She agrees to try again, and reserves the right to change her mind. The treatment that eventually helps does not deliver her childhood home, Idris, or a new wheel. It gives her longer intervals in which Ravash no longer governs every thought. The worst physical distress eases. Sleep begins to return. Food tastes like food rather than something to get through before another need.",
        "One morning she takes a lump of clay and begins a cup. She expects the familiar tremor to ruin its edge. It does not. She turns the piece, smooths a place that needs no smoothing, and waits to see whether her hand will betray her after all. Hanno comes into the room carrying clean cloths. He sees the cup and stops so abruptly that one falls. She tells him to pick it up before he starts crying.",
        "He laughs, and then he does cry. She permits the embrace. Afterward she asks for her worktable back. Recovery still includes visits, the agreed treatment, rest she resents needing, and days when the old desire rises without warning. Alethea calls those days part of what they must learn to care for. Hanno records them reluctantly at first, then faithfully.",
        "Amara takes a small order for hand-built dishes from a woman who knew her work before the wheel was seized. Hanno offers to buy all the pieces himself. ‘Then it would be a gift you allowed me to disguise as work,’ she says. ‘I want the order.’ He offers to cover the firing instead. She agrees to a loan and makes him write it down. For the first time in a long while, an account between them concerns something she means to do next.",
      ],
    },
    {
      id: "the-savior-of-carthara",
      heading: "The Savior of Carthara",
      pov: "Hanno",
      mood: "gold",
      text: [
        "The name cure travels faster than the instructions. By the time a queue reaches the next archway, people are asking for a single bottle that will give them back the years Ravash has taken. Hanno explains that the treatment loosens its hold, that different people respond differently, that follow-up matters. Sometimes they hear him. Sometimes they hear only that he has helped his mother, which is the part of the story he finds hardest to repeat without pride.",
        "They need more vessels, more clean cloth, more people who can prepare a reliable batch under supervision. Hanno rents the neighboring room. Alethea insists that part of it remain for patients rather than production. They work through the figures until midnight. Every extra seat is space he cannot use for shelving; every patient sent away is a person she expects to see again in worse condition. They settle on fewer shelves and a longer working day, which solves the immediate dispute and creates another cost.",
        "Money begins arriving in amounts Hanno is not accustomed to holding. Wealthier households pay for private visits, and those fees keep care available to people who can contribute little. Alethea marks which costs belong to treatment and which to the household. Hanno likes the clarity until a figure limits something he wants to buy. He buys it a week later when the account permits it and feels virtuous for having waited.",
        "A man in the queue recognizes him from the fruit stall. Hanno recognizes the voice first: the vendor who could always make himself heard above Idris. He is old now, leaning heavily on his daughter's arm. ‘Your father would be proud,’ he says. Hanno takes the payment before he can decide whether the remark angers or gratifies him. The daughter asks when to bring her father back, and Alethea answers because Hanno has forgotten to.",
        "There are patients who recover enough to work, families who stop selling one possession after another, and people who need care beyond anything in a bottle. Some return after taking Ravash again. Alethea refuses to put them at the end of the queue as punishment. Hanno agrees in principle. In practice he has to learn to hear their accounts without feeling that his own achievement has been diminished.",
        "One afternoon a little crowd applauds when he steps into the arcade. Somebody calls him the savior of Carthara. He raises a hand to quiet them, but does it slowly. For several moments he is the man to whom the market turns, and every remembered hour behind his father's stall seems to have been leading toward this reversal. Then a woman near the wall asks whether the workshop is still open. He says yes, and carries the applause inside with him.",
        "At home Amara shows him the dishes ready for firing. He admires them properly before mentioning the crowd. She listens, pleased for him, then asks whether he has eaten. He recognizes the question from another city and another morning. He promises he will after the next account is finished.",
      ],
    },
    {
      id: "seeds-of-conflict",
      heading: "Seats at the Table",
      pov: "Numarius",
      mood: "storm",
      text: [
        "Numarius reads two reports concerning the same prosperity. In one, more laborers are returning to their duties and more merchants paying what they owe. In the other, the discreet income that has passed through the Silken Chain is shrinking. His share is not the only one diminished. Corvo's harbor and Vael's garrison have profited alongside his fields, and neither colleague will welcome being asked to absorb a loss for the sake of his public reputation.",
        "He does not think the city was happier when more people needed Ravash. Happiness is a poor quantity to govern by. Grain stored, wages met, ships loaded, debts honored: these can at least be counted. The healer has improved several counts while damaging another, and has done so without owing his rise to a Seat. That last fact concerns Numarius more than the money.",
        "Sinna arrives with a petition concerning standards of preparation. The old apothecary takes time to reach his actual complaint. He speaks of apprentices selling what they do not fully understand, of the need to protect an unsuspecting public. Numarius asks whether he has evidence that the new treatment is harmful. Sinna says haste itself is a danger. ‘It was your training,’ Numarius observes. ‘Do you now wish me to distrust it?’",
        "The man's face tightens. Numarius has no need to destroy his grievance; it may yet be useful. He tells Sinna that proper evidence will receive proper attention. He promises nothing about what those words mean. After the apothecary leaves, he calls for the secretary who arranges civic honors.",
        "Hanno attends the first ceremony in clothes too carefully chosen to look comfortable. His wife stands beside him and asks practical questions about whether recognition will bring help for the rooms where they treat the poor. Numarius answers with admiration for her generosity. She repeats the question. He finds himself liking her less easily than he likes the husband, whose eyes go at once to the crowd.",
        "He praises the pair before the gathered officials and makes sure the city's contribution to their success occupies a respectable part of the speech. Carthara nurtures talent. Carthara welcomes knowledge. Hanno bows when his name is called. Numarius watches him receive the city's gratitude and judges that invitations will be useful. A man invited often enough may come to fear losing his place.",
        "Across the court Sinna stands beneath an arch, half hidden by the guests in front of him. The former apprentice does not see him. Numarius does. For the present he lets the two men keep their different understandings of the afternoon. There will be dinners, conversations, opportunities to discover what each believes he has earned.",
      ],
    },
  ],
};
