import Link from "next/link";
import Image from "next/image";

export const metadata = { title: "Research & media" };
const sources = [
  { title: "The Spear of Zaharaz — Hanno’s Story", detail: "Early narrative; preserved alongside the later draft decisions.", url: "https://docs.google.com/document/d/15yBJhMt-ZnlQByomvJn9YZcW9isOCK_kHsO2p0GcQ6E/edit" },
  { title: "DnD Questionnaire for Suph", detail: "Early character history, beliefs, ambitions, and mechanics.", url: "https://docs.google.com/document/d/1aZ0V575eBJkAhTxrmRZ2HFDqkOWwtknnz_HMRcgc9ac/edit" },
  { title: "DnD Geo Descriptions", detail: "Recovered geography, religious institutions, Sidrat’s lakes, Ruhania, and the Leonin Khanate.", url: "https://docs.google.com/document/d/17GuiNGxrj65hMPzSFAR1PYv3F1-WAHSl24aUPNK4uJ0/edit" },
];

export default function MaterialsPage() {
  return <main className="section-shell"><div className="section-inner"><Link className="book-location" href="/workshop">← Writing room</Link><p className="book-eyebrow mt-8">Research & media</p><h1>The material behind the world.</h1><p className="section-lead">Original ideas, researched history, visual direction, and the sounds that can eventually belong to a place.</p>
    <section className="section-block"><h2>Original documents</h2><div className="notebook-cards">{sources.map((source) => <a href={source.url} key={source.url}><span>Author’s early source</span><h3>{source.title}</h3><p>{source.detail}</p></a>)}</div><p className="section-footnote">Original snapshots are kept in the <a href="https://github.com/Suphian/chronicle/tree/main/worldbuilding/sources">source register</a>. Newer decisions take precedence over superseded details.</p></section>
    <section className="section-block"><h2>Historical influences</h2><div className="notebook-cards"><Link href="/library/ideas/the-pilgrim-ship"><h3>The pilgrim ship</h3><p>The Miri / Mirim attack of 1502 and a proposed adaptation.</p></Link><Link href="/library/ideas/the-teacher-of-the-uplands"><h3>The teacher of the uplands</h3><p>Omar Mukhtar and a proposed resistance story.</p></Link><Link href="/library/ideas/sinna-and-ibn-sina"><h3>Sinna & Ibn Sina</h3><p>Historical scholarship, fictional character, and the question of motive.</p></Link><Link href="/library/ideas/the-surety-quarter"><h3>The Surety Quarter</h3><p>Displacement, labor, and a community’s competing interests.</p></Link></div><p className="section-footnote">Historical research, adopted character traits, and proposed plot additions carry separate labels in each note.</p></section>
    <section className="section-block"><h2>Visual direction</h2><p>Maximalist futuristic Mediterranean and Middle Eastern fantasy: sunlit stone, monumental craft, gardens, water, and intricate instruments.</p><div className="materials-images"><figure><Image src="/images/chronicle/house-of-measures.webp" alt="Sunlit architectural concept overlooking a lake" width={1536} height={1024} /><figcaption>Architectural concept · A visual proposal, not an established location</figcaption></figure><figure><Image src="/images/world/atlas-island-v2.webp" alt="Painted fantasy atlas" width={1536} height={1024} /><figcaption>Atlas artwork · Interactive labels live on the World page</figcaption></figure></div><Link className="book-location" href="/library/visual-direction">Read the visual brief →</Link></section>
    <section className="section-block"><h2>The illustrated edition</h2><p>Every numbered chapter now has three illustrations, with two more in the optional historical tale. Wide landscapes, detailed object studies, and plates beside the prose share an ink-and-watercolor style. These are two examples from the twenty-artwork collection.</p><div className="materials-images"><figure><Image src="/images/plates/carthara-market.webp" alt="Hand-drawn market arcade in Carthara" width={1024} height={1536} /><figcaption>Plate 01 · Beneath the market awnings</figcaption></figure><figure><Image src="/images/plates/apothecary.webp" alt="Hand-drawn apothecary with carved screens and ceramic vessels" width={1024} height={1536} /><figcaption>Plate 02 · An apothecary’s workshop</figcaption></figure></div><p className="section-footnote">Generated with the built-in image tool from the author’s visual references. <a href="https://github.com/Suphian/chronicle/blob/main/public/images/plates/README.md">All artwork, prompts, and provenance</a>.</p></section>
    <section className="section-block"><h2>Sound shelf</h2><p>These synthesized placeholders are available for audition. Playback starts only when you choose a cue.</p><div className="sound-shelf">{[{ id: "ambient-market", title: "Market atmosphere" }, { id: "ambient-wind", title: "Highland wind" }, { id: "ambient-night", title: "Night atmosphere" }, { id: "sfx-page", title: "Page movement" }].map((cue) => <div key={cue.id}><h3>{cue.title}</h3><audio controls preload="none" aria-label={cue.title} src={`/audio/${cue.id}.wav`} /></div>)}</div><Link className="book-location" href="/library/sound-cues">Cue ledger: sources, permissions, and scene associations →</Link></section>
  </div></main>;
}
